input_files:
  manual_scores: "resources/ManualScores/*_scores.csv"
  patient_file: "resources/SB91RT_final_20170821_PrimoLR_EjPnr_orginal.csv"
  tma_map: "resources/Koppling_PathXL_till_TMA-nr.csv"
  immuno_tables: "resources/ImmunoStainings/SWEBCG_pathXL_export_all_230405*.csv"
  original_gex: "resources/GEX_46k_with_gene_names.csv"
  detection_tables: "resources/QuPathDetection/*A_EPCAM_measurements.txt"
  ecc_sizes: "resources/ManualScores/*ecc_sizes.csv"

output_dir: results
