library(tidyverse)
library(RColorBrewer)
library(ggbeeswarm)

setwd("/home/aboffelli/PACC/TMA/Results/")

human_score <- read_tsv("ManualScoreTables/ecc_fold_change.txt")  # Pathologists ECC sizes

n_cells <- table(human_score$Pathologist)  # Calculate the number of ECCs that each pathologist detected.

gmm_table <- read_tsv("QuPathScoreTables/gmm_table.txt")  # Table with GMM values

mean_cps <-gmm_table %>% 
    # Calculate the total mean of each component
    summarize(
        mean_cp1 = mean(mean_cp1),
        mean_cp2 = mean(mean_cp2)) %>% 
    
    # Calculate the fold change of the mean of cp 1 in relation to cp2
    mutate(foldchange= mean_cp1/mean_cp2)

all_cells <- read_tsv("QuPathScoreTables/all_cells_area.txt") %>%  # Table generated by QuPath with the detection values
    mutate(Parent=str_remove(Parent,"_measurements.txt"),   # Isolate the TMA number
           Image = str_remove_all(Image, "-|\\.tif")    # Isolate the core number
           )


# Set a seed for reproducibility
set.seed(1234)
all_cells <- all_cells %>% 
    # Since the number of detections is so high, we subset only 500 random detections.
    slice_sample(n = 500) %>% 

    # Join the gmm values to the table based on the TMA and Core number.
    left_join(gmm_table, by = c("Parent", "Image")) %>% 

    # CAlculate the fold change of the detections based on cp2.
    mutate(FoldChange=Area/mean_cp2) 
    

## Plot ----
fold_change_plot <- human_score %>%
    ggplot(aes(x=PaccArea, y=FoldChange, fill = Pathologist, 
               shape=Pathologist)) +
    
    # Points for the pathologists detections
    geom_point(size=5) + 

    # Points for the detections from QuPath 
    geom_point(data=all_cells, aes(x=Area, y=FoldChange, 
                                      fill='#619CFF'),
                # Smaller and transparent
                alpha=0.5, shape = 21, size=3) + 
    
    # Add the fold change reference lines for cp1 mean, and cp2 (1 since that's the fold change reference)
    geom_hline(yintercept = c(mean_cps$foldchange,1), linetype = c("dashed","dotdash"), 
               color = c("#A50026","#E08214"), size=2) +

    # Fix the labels
    labs(x = "Nuclear Area", y = 'Area Fold Change', fill= 'Type', shape="Type", 
         title = "")+

    # Fix the shape legend. Add the number of cells for each pathologist.
    scale_shape_manual(values = c(21, 24),
                       labels = c(paste0("ECCs Pathologist 1 (n=", 
                                        n_cells["Pathologist 1"], ")"),
                                  paste0("ECCs Pathologist 2 (n=", 
                                               n_cells["Pathologist 2"], ")")
                                  )) +

    # Change the fill colors
    scale_fill_manual(values = c('#619CFF','#FFFF99', "#CAB2D6"))+

    # Have a full y axis from 0 to 9.
    scale_y_continuous(breaks = seq(0, 9, by = 1)) +

    # Remove the fill legend and use shape instead
    guides(fill="none",
           shape = guide_legend(override.aes = list(fill = c('#FFFF99', "#CAB2D6")))) +

    # Increase the text font
    theme_classic(base_size = 30)+

    # Position the legend inside the plot and increase the font
    theme(legend.position = c(0.82,0.26),
          legend.title = element_text(size = 18),
          legend.text = element_text(size = 18))

# Save the tif image.
ggsave("~/PACC/TMA/Results/pathologist_scatterplot.tif", fold_change_plot, width = 390, height=240, units = "mm")
